### PR TITLE
Fix set include external ids

### PR DESCRIPTION
**Pull request by calvernaz**
Fix setting the external id attribute.

### CODE REVIEW

**Review by sriprasanna — APPROVED** [review]
👍

**Comment by sriprasanna** [comment]
Thanks @calvernaz. Looks like Travis is acting strange once the build passes I will merge your PR.

**Comment by calvernaz** [comment]
> Thanks @calvernaz. Looks like Travis is acting strange once the build passes I will merge your PR.

I've seen this error before, there is one related https://github.com/zalando/logbook/pull/515 and the suggestion is to change to openjdk

**Comment by sriprasanna** [comment]
@calvernaz Can you update this branch with the latest changes in Master(from https://github.com/CurrencyFair/OneSignal-Java-SDK/pull/24)? That should fix the build and I will merge this after.

**Comment by calvernaz** [comment]
@sriprasanna thank you. done

**Pull request merged**
