### PR TITLE
Support `include_external_user_ids` for targeting external user IDs.

### PR DESCRIPTION
**Pull request by ndarilek**
Please let me know if I missed anything with this. I need this functionality, and am not sure if there are any additional integration points I may have missed. Thanks!

### CODE REVIEW

**Review by sriprasanna — APPROVED** [review]
👍 Looks good to me to merge

**Comment by ndarilek** [comment]
Thanks! Would like to see this in a published release, since I'm 
building a service that needs it, and I'm having a hard time using my 
custom build while still pulling in the release's transitive dependencies.

**Comment by ndarilek** [comment]
Any updates on this? Really need it on my end.

Thanks.

**Comment by bavicj** [comment]
+1 for this PR

**Comment by molleafauss** [comment]
Apologies, @ndarilek there's been a misunderstanding with my colleague. I'll merge this soon and see if I can release.

**Comment by ndarilek** [comment]
Thanks a bunch!

**Pull request merged**
